node {
	stage('SCM Checkout'){
		git branch: 'master', credentialsId: 'GitHubPassword', url: 'https://github.com/UdayVishal/MFRPClaimsManagementSystem.git'
	}
	stage('Install'){
		def mvnHome = tool name: 'Maven 3.8', type: 'maven'
		bat "${mvnHome}/bin/mvn -DskipTests clean install"
	}
	stage('Test'){
		def mvnHome = tool name: 'Maven 3.8', type: 'maven'
		bat "${mvnHome}/bin/mvn test"
	}
	stage('Package'){
		def mvnHome = tool name: 'Maven 3.8', type: 'maven'
		bat "${mvnHome}/bin/mvn package"
	}
	
}
